# Generated by Django 4.2.6 on 2023-12-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RDV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('sexe', models.CharField(max_length=10, null=True)),
                ('age', models.IntegerField(null=True)),
                ('Date', models.DateField(null=True)),
                ('Heure', models.TimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sexe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donnee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('sexe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.sexe')),
            ],
        ),
    ]
